//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Student_Number { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public System.DateTime Student_Birtdate { get; set; }
        public long Student_TC_NO { get; set; }
    }
}
