//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int ID { get; set; }
        public string TeacherName { get; set; }
        public string TeacherSurname { get; set; }
        public int Teacher_SicilNo { get; set; }
        public long Teacher_TC_NO { get; set; }
    }
}
